module.exports = labels = {
    NO_DATA: 'Brak danych!',
    NO_DATA_IN_SUCH_PERIOD: 'Brak danych w tym okresie!',
    NO_COMMAND: 'Brak takiej komendy, wpisz `pomoc`',
    RESULTS_WRONG_DATE_FORMAT: 'Daty muszą być w formacie `YYYY-MM-DD`',
    ADD_PLAYER_WRONG_FORMAT: 'Musisz podać imię, nazwisko oraz pseudonim!\nNa przykład: \`dodaj zawodnika Jan Kowalski kendokoluszki\`',
    ADD_PLAYER_SUCCESS: 'Dodano nowego ludzika - *{0} \'{1}\' {2}*',
    ADD_PLAYER_ALIAS_NO_EXISTS: 'Zawodnik o pseudonimie {0} nie istnieje!',
    IN_A_ROW: 'pod rząd',
    NO_SUCH_PERIOD: 'Nie ma takiego okresu, wpisz `pomoc`',
    WINNER_APPENDIX: ' - Zwycięzca',
    NTH_PLACE: '{0} miejsce',
    PLAYOFF_RESULTS: '(dogrywka: {0} w {1})',
    IN_SMTH: ' w {0}',
    TOURNAMENT_WON_ONE: '{0} turniej wygrany',
    TOURNAMENT_WON_FEW: '{0} turnieje wygrane',
    TOURNAMENT_WON_MANY: '{0} turniejów wygranych',
    TOURNAMENT_LOST_ONE: '{0} turniej przegrany',
    TOURNAMENT_LOST_FEW: '{0} turnieje przegrane',
    TOURNAMENT_LOST_MANY: '{0} turniejów przegranych',
    TOURNAMENT_ONE: '{0} turnieju',
    TOURNAMENT_MANY: '{0} turniejach',
    ROUND_ONE: '{0} rundzie',
    ROUND_MANY: '{0} rundach',
    SHOOT_ONE: '{0} rzut',
    SHOOT_FEW: '{0} rzuty',
    SHOOT_MANY: '{0} rzutów'
};